name: Feature Request
description: If you have a feature request for the app. Please use this template to help improve the app.
title: "[FEATURE REQUEST]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    id: message
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    id: preflight-checklist
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have read and I agree to follow the [support disclaimer](https://github.com/Paperback-iOS/app#support-disclaimer).
          required: true
        - label: I am sure that my feature request has nothing to with third party extensions.
          required: true          
        - label: I am using the latest available Paperback version (currently 0.8).
          required: true
        - label: I have searched the [issue tracker](https://github.com/Paperback-iOS/app/issues) for a feature request that matches the one I want to file, without success.
          required: true
  - type: dropdown
    id: device-types
    attributes:
      label: What type of Apple device is the feature request for?
      multiple: true
      options:
        - All device types
        - iPhone
        - iPad
        - Mac computer
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature you would like to see added.
      placeholder: Tell us what you want!
    validations:
      required: true
  - type: textarea
    id: feature-motivation
    attributes:
      label: Feature Motivation
      description: Explain how the feature will improve the app.
      placeholder: Tell us the about the benefits!
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Anything Else?
      description: |
        Links? References? Anything that will give us more context about the feature which you are requesting!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Images, links, ...
    validations:
      required: false
